### ISSUE TITLE
SeeQR 8.0 Issues

### ISSUE THREAD

**Issue by Frynoceros** [open-source-labs/SeeQR#80]
MySQL

- [x] Unable to import files into SeeQR directly
- --MySQL error prevents import without direct install of brew of all MySQL.
- [ ] No export option available.
- --Need to fine-tune the query for MySQL.
- [x] Unable to duplicate databases
- --Need Query adjustment and fix of copy query.
- [x] Drop database after switching to postgres will sometimes cause issue where unable to delete selected database.
- --Most likely has to do with current and last database being reassigned incorrectly.
- [ ] MySQL execution query doesn’t function consistently.
-- Need to see how data is being returned from query to correctly translate it to the frontend.

ERD

- [x] Easier viewing options. Pan to scroll or click to move options. 
- --Difficult to navigate around the ERD when the database is large.
- [ ] MySQL tables don’t populate in the correct location when being imported.
- --Top table node doesn’t connect to corresponding columns causing tables to look separated.
--- Need to see how data is being returned from query and translated to frontend.
- [x] MiniMap receives greater functionality and allows for faster movement.
- --Needs click to navigate feature and pan to scroll for fast movement.
- --Zoomed very far out with MySQL and difficult to see tables.
- [ ] Optimized query to load database quicker.
- --Large databases will take awhile to load. Can benefit from optimized query.
- [x] Saving ERD when using MySQL is inconsistent.
- --Additional tables fail to save after multiple tables have been added and saved. 

Table View

- [x] DummyData button doesn’t work
- --Query doesn’t provide dummy data.
- --Needs to be functional with MySQL
- [x] Table viewing from the table view needs dropdown view 
- --Difficult to navigate around when there are a lot of tables

Quality of life

- [x] Delete button doesn’t ask for confirmation
- -- Seen in both column and sidebar view.
- [x] Export icon next to duplicate and trash icon
- [ ] Dependency issues when doing NPM install for Mac.
- --Need to move on from deprecated MUI.
- [x]  Scrollbar for sidebar when lots of databases are connected.

**Comment by paulinekpn** [comment]
Unable to checkmark the first section of the issues mentioned. See below for an update of the resolved issues:

[X] - Unable to import files into SeeQR directly
--MySQL error prevents import without direct install of brew of all MySQL.
[ ] -No export option available.
--Need to fine-tune the query for MySQL.
[X] Unable to duplicate databases
--Need Query adjustment and fix of copy query.
[ ] Drop database after switching to postgres will sometimes cause issue where unable to delete selected database.
--Most likely has to do with current and last database being reassigned incorrectly.
[ ] MySQL execution query doesn’t function consistently.
-- Need to see how data is being returned from query to correctly translate it to the frontend.
